
_target_: project.model.task_balancing.TaskBalanceMTL

config:
  n_tasks: 641
  balance: "None" 
  balance_method: "Sum"
  K: 4
  T: 4
  alpha_balance: 0.5 #alpha_balance: 0.5 # So this is a tuning parameter for the task balancing, which determines the balance between the different tasks. 
# alpha_balance is often defined by 1 / num_tasks. 
