defaults:
  - data: spike.yaml  
  - model: MH.yaml

  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# Pytorch lightning trainer's argument
# default flags are commented to avoid clustering the hyperparameters
trainer:
  benchmark: True
  max_epochs: 10
  log_every_n_steps: 1

